### ISSUE TITLE
QGIS 2.8.1 requires spatialite

### ISSUE THREAD

**Issue by eseifert** [rion-overlay/rion-overlay#190]
The ebuild fails to compile without spatialite when the USE flag is not set. The current ebuild has a USE flag for spatialite support, but according to the CMake file it is a hard dependency. I tried to modify the CMake build to make it optional, but it seems that QGIS relies on spatialite.

**Comment by eegorov** [comment]
Ok. I'll remove USE=spatialite

**Comment by eegorov** [comment]
Please test. Reopen, if there are problems.
