### ISSUE TITLE
rts_bpp fail to compile

### ISSUE THREAD

**Issue by latot** [rion-overlay/rion-overlay#191]
Hi, here a patch https://gist.github.com/latot/cc26184d5f0701dd66c2 from here http://forum.ubuntu-fr.org/viewtopic.php?id=1441421

err:

>>> Source configured.
>>> Compiling source in /var/tmp/portage/sys-libs/rts_bpp-1.1/work/rts_bpp ...
ln: failed to create symbolic link ‘Module.symvers’: File exists
 * Preparing rts_bpp module
make -j8 HOSTCC=x86_64-pc-linux-gnu-gcc CROSS_COMPILE=x86_64-pc-linux-gnu- 'LDFLAGS=-m elf_x86_64' 
cp -f ./define.release ./define.h
make -C /lib/modules/3.19.3-gentoo/build/ SUBDIRS=/var/tmp/portage/sys-libs/rts_bpp-1.1/work/rts_bpp modules
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/usr/src/linux-3.19.3-gentoo-r0'
  CC [M]  /var/tmp/portage/sys-libs/rts_bpp-1.1/work/rts_bpp/rtsx.o
/var/tmp/portage/sys-libs/rts_bpp-1.1/work/rts_bpp/rtsx.c: In function ‘proc_info’:
/var/tmp/portage/sys-libs/rts_bpp-1.1/work/rts_bpp/rtsx.c:141:41: error: macro "__TIME__" might prevent reproducible builds [-Werror=date-time]
  SPRINTF("        Build: %s\n", __TIME__);
                                         ^
/var/tmp/portage/sys-libs/rts_bpp-1.1/work/rts_bpp/rtsx.c: At top level:
/var/tmp/portage/sys-libs/rts_bpp-1.1/work/rts_bpp/rtsx.c:259:2: error: unknown field ‘proc_info’ specified in initializer
  .proc_info =   proc_info,
  ^
/var/tmp/portage/sys-libs/rts_bpp-1.1/work/rts_bpp/rtsx.c:259:2: warning: initialization from incompatible pointer type
/var/tmp/portage/sys-libs/rts_bpp-1.1/work/rts_bpp/rtsx.c:259:2: warning: (near initialization for ‘rtsx_host_template.proc_dir’)
/var/tmp/portage/sys-libs/rts_bpp-1.1/work/rts_bpp/rtsx.c: In function ‘rtsx_control_thread’:
/var/tmp/portage/sys-libs/rts_bpp-1.1/work/rts_bpp/rtsx.c:496:7: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘u64’ [-Wformat=]
       chip->srb->device->id, chip->srb->device->lun);
       ^
/var/tmp/portage/sys-libs/rts_bpp-1.1/work/rts_bpp/rtsx.c:502:7: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘u64’ [-Wformat=]
       chip->srb->device->id, chip->srb->device->lun);
       ^
/var/tmp/portage/sys-libs/rts_bpp-1.1/work/rts_bpp/rtsx.c: In function ‘rtsx_probe’:
/var/tmp/portage/sys-libs/rts_bpp-1.1/work/rts_bpp/rtsx.c:900:35: error: macro "__TIME__" might prevent reproducible builds [-Werror=date-time]
  printk(KERN_INFO "--- %s ---\n", __TIME__);
                                   ^
cc1: some warnings being treated as errors
scripts/Makefile.build:257: recipe for target '/var/tmp/portage/sys-libs/rts_bpp-1.1/work/rts_bpp/rtsx.o' failed
make[2]: *** [/var/tmp/portage/sys-libs/rts_bpp-1.1/work/rts_bpp/rtsx.o] Error 1
Makefile:1382: recipe for target '_module_/var/tmp/portage/sys-libs/rts_bpp-1.1/work/rts_bpp' failed
make[1]: *** [_module_/var/tmp/portage/sys-libs/rts_bpp-1.1/work/rts_bpp] Error 2
make[1]: Leaving directory '/usr/src/linux-3.19.3-gentoo-r0'
Makefile:35: recipe for target 'default' failed
make: *** [default] Error 2
 * ERROR: sys-libs/rts_bpp-1.1::rion failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=sys-libs/rts_bpp-1.1::rion'`,
 * the complete build log and the output of `emerge -pqv '=sys-libs/rts_bpp-1.1::rion'`.
 * The complete build log is located at '/var/tmp/portage/sys-libs/rts_bpp-1.1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sys-libs/rts_bpp-1.1/temp/environment'.
 * Working directory: '/var/tmp/portage/sys-libs/rts_bpp-1.1/work/rts_bpp'
 * S: '/var/tmp/portage/sys-libs/rts_bpp-1.1/work/rts_bpp'

>>> Failed to emerge sys-libs/rts_bpp-1.1, Log file:

>>>  '/var/tmp/portage/sys-libs/rts_bpp-1.1/temp/build.log'

kernel 3.19.3

thx.

**Comment by Ri0n** [comment]
I don't think this package is still required. The driver is in kernel now.
I'm going to drop it

**Comment by latot** [comment]
in the kernel 3.19.3 don't is available.

**Comment by Ri0n** [comment]
As far as I know one of MFD_RTSX_PCI or MFD_RTSX_USB should work instead of this driver.
try it.

**Comment by latot** [comment]
mm, you are right, with that conf more some other parts works again, thx.

**Comment by Ri0n** [comment]
For some reason RTSX_PCI stopped working for me. So I've brought the driver back.
