### ISSUE TITLE
freshplayerplugin ebuild has a 0.2.4-cmake.patch, but it is not in the overlay.

### ISSUE THREAD

**Issue by sarnex** [rion-overlay/rion-overlay#198]
Hi. I'm trying to emerge www-plugins/freshplayerplugin-9999. In the ebuild, it says `PATCHES=( "${FILESDIR}/0.2.4-cmake.patch" )` but this file isn't present in the overlay.

Thanks,
sarnex

**Comment by alexws54tk** [comment]
Hi, @sarnex . The file you a interesting is available at master portage tree in `/usr/portage/www-plugins/freshplayerplugin/files` directory.

**Comment by sarnex** [comment]
@alexws54tk Ok thanks. But I think you should still copy the folder into your overlay.

Thanks again

**Comment by Ri0n** [comment]
I've disabled the patch. thanks for the report

**Comment by sarnex** [comment]
It compiles without issue now. Thanks.
