### ISSUE TITLE
net-im/ejabberd-9999: No rule to make target 'doc'

### ISSUE THREAD

**Issue by l29ah** [rion-overlay/rion-overlay#200]
make -j3 doc
make: *** No rule to make target 'doc'.  Stop.

**Comment by Ri0n** [comment]
ejabberd removed

**Comment by msva** [comment]
на Peosody переехал? :D

**Comment by Ri0n** [comment]
Не. Просто устраивает то, что есть в портаже.  А времени на поддержку 9999 особо нет
