### ISSUE TITLE
sci-geosciences/qgis-2.12.0::rion: missing "grass" directory

### ISSUE THREAD

**Issue by MincingWords** [rion-overlay/rion-overlay#204]
Emerging subject ebuild dies as follows:

-- Installing: /var/tmp/portage/sci-geosciences/qgis-2.12.0/image/usr/lib64/python2.7/site-packages/pyspatialite/_spatialite.so
-- Removed runtime path from "/var/tmp/portage/sci-geosciences/qgis-2.12.0/image//usr/lib64/python2.7/site-packages/pyspatialite/_spatialite.so"
-- Installing: /var/tmp/portage/sci-geosciences/qgis-2.12.0/image/usr/lib64/python2.7/site-packages/pyspatialite/__init__.py
-- Installing: /var/tmp/portage/sci-geosciences/qgis-2.12.0/image/usr/lib64/python2.7/site-packages/pyspatialite/dbapi2.py
-- Installing: /var/tmp/portage/sci-geosciences/qgis-2.12.0/image/usr/lib64/python2.7/site-packages/pyspatialite/dump.py
find: `/var/tmp/portage/sci-geosciences/qgis-2.12.0/image//usr/share/qgis/grass/scripts': No such file or directory
 * ERROR: sci-geosciences/qgis-2.12.0::rion failed (install phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line   93:  Called src_install
 *   environment, line 4095:  Called python_fix_shebang '/var/tmp/portage/sci-geosciences/qgis-2.12.0/image//usr/share/qgis/grass/scripts'
 *   environment, line 3457:  Called die
 * The specific snippet of code:
 *       for path in "$@";
 * 
 * If you need support, post the output of `emerge --info '=sci-geosciences/qgis-2.12.0::rion'`,
 * the complete build log and the output of `emerge -pqv '=sci-geosciences/qgis-2.12.0::rion'`.
 * The complete build log is located at '/var/tmp/portage/sci-geosciences/qgis-2.12.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sci-geosciences/qgis-2.12.0/temp/environment'.
 * Working directory: '/var/tmp/portage/sci-geosciences/qgis-2.12.0/work/qgis-2.12.0'
 * S: '/var/tmp/portage/sci-geosciences/qgis-2.12.0/work/qgis-2.12.0'

>>> Failed to emerge sci-geosciences/qgis-2.12.0, Log file:

>>>  '/var/tmp/portage/sci-geosciences/qgis-2.12.0/temp/build.log'

 * Messages for package sci-geosciences/qgis-2.12.0:

 * ERROR: sci-geosciences/qgis-2.12.0::rion failed (install phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line   93:  Called src_install
 *   environment, line 4095:  Called python_fix_shebang '/var/tmp/portage/sci-geosciences/qgis-2.12.0/image//usr/share/qgis/grass/scripts'
 *   environment, line 3457:  Called die
 * The specific snippet of code:
 *       for path in "$@";
 * 
 * If you need support, post the output of `emerge --info '=sci-geosciences/qgis-2.12.0::rion'`,
 * the complete build log and the output of `emerge -pqv '=sci-geosciences/qgis-2.12.0::rion'`.
 * The complete build log is located at '/var/tmp/portage/sci-geosciences/qgis-2.12.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sci-geosciences/qgis-2.12.0/temp/environment'.
 * Working directory: '/var/tmp/portage/sci-geosciences/qgis-2.12.0/work/qgis-2.12.0'
 * S: '/var/tmp/portage/sci-geosciences/qgis-2.12.0/work/qgis-2.12.0'

'emerge --info '=sci-geosciences/qgis-2.12.0::rion' output: 

Portage 2.2.20.1 (python 2.7.10-final-0, default/linux/amd64/13.0, gcc-4.9.3, glibc-2.21-r1, 4.0.5-gentoo x86_64)
=================================================================
                         System Settings
=================================================================
System uname: Linux-4.0.5-gentoo-x86_64-Intel-R-_Xeon-R-_CPU_X5570_@_2.93GHz-with-gentoo-2.2
KiB Mem:    65968624 total,   5311900 free
KiB Swap:   33554428 total,  33554376 free
Timestamp of repository gentoo: Thu, 10 Dec 2015 05:15:01 +0000
sh bash 4.3_p39
ld GNU ld (Gentoo 2.25.1 p1.1) 2.25.1
distcc 3.2rc1 x86_64-pc-linux-gnu [disabled]
app-shells/bash:          4.3_p39::gentoo
dev-java/java-config:     2.2.0::gentoo
dev-lang/perl:            5.20.2::gentoo
dev-lang/python:          2.7.10-r1::gentoo, 3.4.3::gentoo
dev-util/cmake:           3.3.1-r1::gentoo
dev-util/pkgconfig:       0.28-r2::gentoo
sys-apps/baselayout:      2.2::gentoo
sys-apps/openrc:          0.18.4::gentoo
sys-apps/sandbox:         2.6-r1::gentoo
sys-devel/autoconf:       2.13::gentoo, 2.69::gentoo
sys-devel/automake:       1.11.6-r1::gentoo, 1.14.1::gentoo, 1.15::gentoo
sys-devel/binutils:       2.25.1-r1::gentoo
sys-devel/gcc:            4.9.3::gentoo
sys-devel/gcc-config:     1.7.3::gentoo
sys-devel/libtool:        2.4.6::gentoo
sys-devel/make:           4.1-r1::gentoo
sys-kernel/linux-headers: 3.18::gentoo (virtual/os-headers)
sys-libs/glibc:           2.21-r1::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: rsync
    sync-uri: rsync://rsync25.us.gentoo.org/gentoo-portage/
    priority: -1000

rion
    location: /var/lib/layman/rion
    masters: gentoo
    priority: 0

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="* -@EULA"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=corei7 -O2 -pipe -fomit-frame-pointer"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/lib64/libreoffice/program/sofficerc /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo"
CXXFLAGS="-march=corei7 -O2 -pipe -fomit-frame-pointer"
DISTDIR="/usr/portage/distfiles"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync news parallel-fetch preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="http://distfiles.gentoo.org"
LANG="en_US.utf8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j17"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages"
PORTAGE_TMPDIR="/var/tmp"
USE="X acl ads amd64 bacula-nosd berkdb bzip2 cli cracklib crypt cxx dri fortran gdbm iconv jpeg mmx mmxext modules multilib ncurses netcdf nls nptl openmp pam pam_krb5 pcre png postgis postscript readline seccomp session sse sse2 ssl system-cairo tcpd tiff tk unicode xattr zlib" ABI_X86="64" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="kexi words flow plan sheets stage tables krita karbon braindump author" CAMERAS="ptp2" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="mmx mmxext popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="evdev" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-5" PYTHON_SINGLE_TARGET="python2_7" PYTHON_TARGETS="python2_7 python3_4" RUBY_TARGETS="ruby20 ruby21" USERLAND="GNU" VIDEO_CARDS="mga" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, USE_PYTHON

Emerge of sci-geosciences/qgis-2.10.0::rion hit a similar problem, saying "find: `/var/tmp/portage/sci-geosciences/qgis-2.10.1/image//usr/share/qgis/grass/scripts': No such file or directory"

In the case of qgis-2.12.0, the contents of /var/tmp/portage/sci-geosciences/qgis-2.12.0/image/usr/share/qgis/ are: "doc  FindQGIS.cmake  i18n  images  python  resources  svg". That there is no "grass" directory seems to be the problem.  

If it helps, 2.10.0 had emerged successfully on this machine; the problem with emerging 2.10.0 occurred after adding the netcdf USE flag via make.conf. Unfortunately, backing out the netcdf USE flag addition didn't help anything, so I'm at a loss as to why qgis 2.10.0 ever built.

**Comment by eegorov** [comment]
Please show output 
emerge -pv qgis grass
and full build.log of qgis

**Comment by MincingWords** [comment]
Thank you - GRASS isn't on the machine; it wants me to keyword =sci-libs/xdrfile-1.1.1 and =sci-geosciences/grass-7.0.1-r4 for ~amd64 and add the cairo USE flag for >=dev-python/wxpython-2.8.12.1-r2:2.8. Shall I do that and report back?

Any reason why grass wasn't a dependency of qgis-2.12.0? In the meantime, I'm attaching qgis' build log and here is the output of emerge -pv qgis grass:

# emerge -pv qgis grass

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild  N    ~] sci-libs/xdrfile-1.1.1::gentoo  USE="fortran -static-libs" ABI_X86="(64) -32 (-x32)" 371 KiB
[ebuild  N     ] x11-proto/printproto-1.0.5-r1::gentoo  ABI_X86="(64) -32 (-x32)" 218 KiB
[ebuild  N     ] x11-libs/libXp-1.0.3::gentoo  USE="-static-libs" ABI_X86="(64) -32 (-x32)" 310 KiB
[ebuild  NS    ] x11-libs/wxGTK-2.8.12.1-r1:2.8::gentoo [3.0.2.0-r1:3.0::gentoo] USE="X tiff (-aqua) -debug -doc -gnome -gstreamer -odbc -opengl -pch -sdl" 30,578 KiB
[ebuild  N     ] dev-python/wxpython-2.8.12.1-r2:2.8::gentoo  USE="cairo -doc -examples -opengl" PYTHON_TARGETS="python2_7" 0 KiB
[ebuild     U ~] sci-geosciences/qgis-2.12.0::rion [2.10.1::rion] USE="postgres python -examples -grass -gsl -mapserver {-test}" PYTHON_TARGETS="python2_7" 0 KiB
[ebuild  N     ] media-libs/freeglut-3.0.0::gentoo  USE="-debug -static-libs" ABI_X86="(64) -32 (-x32)" 410 KiB
[ebuild  N     ] media-libs/ftgl-2.1.3_rc5::gentoo  USE="-static-libs" 692 KiB
[ebuild  N     ] media-libs/libprojectm-2.1.0-r1::gentoo  USE="openmp -debug" VIDEO_CARDS="-nvidia" 30,401 KiB
[ebuild  N    ~] sci-geosciences/grass-7.0.1-r4::gentoo  USE="X cxx nls openmp png readline tiff -blas -debug -fftw -geos -lapack -liblas -mysql -netcdf -odbc -opencl -opengl -postgres -sqlite -threads -truetype" PYTHON_TARGETS="python2_7" 32,943 KiB

Total: 10 packages (1 upgrade, 8 new, 1 in new slot), Size of downloads: 95,919 KiB

The following keyword changes are necessary to proceed:
 (see "package.accept_keywords" in the portage(5) man page for more details)
# required by sci-geosciences/grass-7.0.1-r4::gentoo
# required by grass (argument)
=sci-libs/xdrfile-1.1.1 ~amd64
# required by grass (argument)
=sci-geosciences/grass-7.0.1-r4 ~amd64

The following USE changes are necessary to proceed:
 (see "package.use" in the portage(5) man page for more details)
# required by sci-geosciences/grass-7.0.1-r4::gentoo[X]
# required by grass (argument)
[build.log.txt](https://github.com/rion-overlay/rion-overlay/files/59013/build.log.txt)

**Comment by eegorov** [comment]
GRASS is optional dependency/
