### ISSUE TITLE
skypeforlinux: add v4l deps

### ISSUE THREAD

**Issue by mpkh** [rion-overlay/rion-overlay#216]
```
-       x11-libs/pango[${MULTILIB_USEDEP}]"
+       x11-libs/pango[${MULTILIB_USEDEP}]
+       media-libs/libv4l[${MULTILIB_USEDEP}]
+       media-tv/v4l-utils[${MULTILIB_USEDEP}]
+       "

```

**Comment by Ri0n** [comment]
are those deps from dep package? I don't see any utils in rpm

**Comment by mpkh** [comment]
@Ri0n not sure if both of them is needed or just libv4l is fine (also second one includes first one) but one of them is needed for sure - skype just will not work without them. I think MS devs expect their ubuntu have it library installed with no reason.

**Comment by Ri0n** [comment]
thanks. added just libv4l
