### ISSUE TITLE
make myrulib_FbNotebook.o Error 1

### ISSUE THREAD

**Issue by zerrxs** [rion-overlay/rion-overlay#220]
full log: https://pastebin.com/g4xfCVMt
This error occurs on both versions of the ebuilds
Please help me fix this.

**Comment by Ri0n** [comment]
I'll review this. But since upstream doesn't support this anymore, probably I'll remove this package from the overlay

**Comment by zerrxs** [comment]
in archlinux this package is emerging from aur without any problems, I tested personally a couple of weeks ago

In any case, thanks
