### ISSUE TITLE
ERROR: x11-themes/qtcurve-9999-r1::rion  ... EAPI=6 is not supported

### ISSUE THREAD

**Issue by RarogCmex** [rion-overlay/rion-overlay#228]
It seems like error in simbol... EAPI=6 is still supports by some ebuilds.
Похоже, там какие-то странности с символами, вроде бы до устаревания EAPI=6 еще далеко
 * Call stack:
 | *                ebuild.sh, line 616:  Called source '/var/lib/layman/rion/x11-themes/qtcurve/qtcurve-9999-r1.ebuild'
 *   qtcurve-9999-r1.ebuild, line   7:  Called inherit 'kde5' 'cmake-multilib' 'git-r3'
 *                ebuild.sh, line 317:  Called __qa_source '/usr/portage/gentoo/eclass/kde5.eclass'
 *                ebuild.sh, line 112:  Called source '/usr/portage/gentoo/eclass/kde5.eclass'
 *              kde5.eclass, line  35:  Called inherit 'cmake-utils' 'flag-o-matic' 'kde5-functions' 'virtualx' 'xdg'
 *                ebuild.sh, line 317:  Called __qa_source '/usr/portage/gentoo/eclass/kde5-functions.eclass'
 *                ebuild.sh, line 112:  Called source '/usr/portage/gentoo/eclass/kde5-functions.eclass'
 *    kde5-functions.eclass, line  22:  Called die
 * The specific snippet of code:
 *      *) die "EAPI=${EAPI:-0} is not supported" ;;
 * 
 * If you need support, post the output of `emerge --info '=x11-themes/qtcurve-9999-r1::rion'`,
 * the complete build log and the output of `emerge -pqv '=x11-themes/qtcurve-9999-r1::rion'`.
 * Working directory: '/usr/lib64/python3.6/site-packages'
 * S: '/var/tmp/portage/x11-themes/qtcurve-9999-r1/work/qtcurve-9999'

**Comment by RarogCmex** [comment]
[emerge --info](https://github.com/rion-overlay/rion-overlay/files/3746572/rion.txt)

**Comment by eegorov** [comment]
https://github.com/rion-overlay/rion-overlay/commit/2573c7b3b9d30d066146cbf56eece6c6384e60cf
