### ISSUE TITLE
x11-themes/qtcurve-9999-r1::rion kde5.eclass could not be found by inherit()

### ISSUE THREAD

**Issue by RarogCmex** [rion-overlay/rion-overlay#230]
Calculating dependencies / * ERROR: x11-themes/qtcurve-9999-r1::rion failed (depend phase):
 *   kde5.eclass could not be found by inherit()
 * 
 * Call stack:
 *                ebuild.sh, line 609:  Called source '/var/db/repos/rion/x11-themes/qtcurve/qtcurve-9999-r1.ebuild'
 *   qtcurve-9999-r1.ebuild, line   7:  Called inherit 'kde5' 'cmake-multilib' 'git-r3'
 *                ebuild.sh, line 290:  Called die
 * The specific snippet of code:
 *              [[ -z ${location} ]] && die "${1}.eclass could not be found by inherit()"
 * 
 * If you need support, post the output of `emerge --info '=x11-themes/qtcurve-9999-r1::rion'`,
 * the complete build log and the output of `emerge -pqv '=x11-themes/qtcurve-9999-r1::rion'`.
 * Working directory: '/usr/lib/pypy3.6/site-packages'
 * S: '/var/tmp/portage/x11-themes/qtcurve-9999-r1/work/qtcurve-9999'
... done!

Думаю, все понятно.

**Comment by Ri0n** [comment]
Удалю его. В портаже тоже есть 9999. Сколько помню он немного другой. Но если автор ебилда из оверлея объявится то вернет из гит истории

**Comment by eegorov** [comment]
Да вроде не актуально уже. Тот ебилд был со сборкой под 32-битные Qt4. Если кому-нибудь нужно будет - пишите мне в личку
