### ISSUE TITLE
linphone-desktop-4.1.1: Unable to fetch the sources

### ISSUE THREAD

**Issue by penguin-ff** [rion-overlay/rion-overlay#234]
Hi Sergey,

if i start "from zero" (no fetches in the past), your ebuild dies while fetching the sources...

Last Message:
 
    Fetching https://gitlab.linphone.org/BC/public/mbedtls.git ...
    git fetch https://gitlab.linphone.org/BC/public/mbedtls.git --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +HEAD:refs/git-r3/HEAD
    fatal: could not read Username for 'https://gitlab.linphone.org': terminal prompts disabled
     * Fetching git://git.linphone.org/mbedtls.git ...
    git fetch git://git.linphone.org/mbedtls.git --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +HEAD:refs/git-r3/HEAD
    fatal: remote error: access denied or repository not exported: /mbedtls.git
     * ERROR: net-voip/linphone-desktop-4.1.1::rion failed (unpack phase):
     *   Unable to fetch from any of EGIT_REPO_URI

Can you reproduce this? I tried on several days - same result. I don't know if it's a "mistake" in your ebuild but cloning with the commands suggested at https://gitlab.linphone.org/BC/public/linphone-desktop, for example:
    git clone https://gitlab.linphone.org/BC/public/linphone-desktop.git --recursive

works fine and source is downloaded.

Any ideas or help from your side? I'm so curious to test your ebuild and the software
Thanks!

**Comment by penguin-ff** [comment]
The above "fatal: could not read Username for 'https://gitlab.linphone.org': terminal prompts disabled" i believe is not the problem - fetching webrtc.git works fine despite this message:

* Fetching https://gitlab.linphone.org/BC/public/webrtc.git ...
git fetch https://gitlab.linphone.org/BC/public/webrtc.git --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +HEAD:refs/git-r3/HEAD
fatal: could not read Username for 'https://gitlab.linphone.org': terminal prompts disabled
 * Fetching git://git.linphone.org/webrtc.git ...
git fetch git://git.linphone.org/webrtc.git --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +HEAD:refs/git-r3/HEAD
remote: Counting objects: 125083, done.

**Comment by penguin-ff** [comment]
I can successfully fetch the sources with the following "patch", but after it doesn't compile for reasons:

-EGIT_CLONE_TYPE=shallow
-
-inherit l10n multilib pax-utils cmake-utils git-r3
+inherit l10n multilib pax-utils cmake-utils
 
 DESCRIPTION="Video softphone based on the SIP protocol"
 HOMEPAGE="http://www.linphone.org/"
-EGIT_REPO_URI="https://gitlab.linphone.org/BC/public/linphone-desktop.git"
-EGIT_COMMIT="${PV}"
-EGIT_MIRROR_URI="https://gitlab.linphone.org/BC/public/"
+SRC_URI="https://github.com/BelledonneCommunications/linphone-desktop/archive/${PV}.tar.gz"

**Comment by Ri0n** [comment]
Yes. It's currently broken. I'll remove the package soon.
It's impossible to fix it.
Belledonne distributes appimages as well. So it's way easier to install linphone than bothering with the ebuild.

**Comment by Ri0n** [comment]
Well you know, I can add an ebuild to install that appimage :)

**Comment by penguin-ff** [comment]
It looks like Alpine succeeded packaging 4.3.1 (no Appimage) - Can we go that way?
    https://git.alpinelinux.org/aports/tree/testing/linphone/APKBUILD

**Comment by Ri0n** [comment]
sorry. lack of motivation. I removed this garbage.
