### ISSUE TITLE
samsung-unified-driver - ED does not have a trailing slash

### ISSUE THREAD

**Issue by ngleb** [rion-overlay/rion-overlay#237]
In the ebuild for net-print/samsung-unified-driver-1.0.39, EAPI version is 7. This ebuild currently does not work.

You have [this line](https://github.com/rion-overlay/rion-overlay/blob/master/net-print/samsung-unified-driver/samsung-unified-driver-1.00.39.ebuild#L81) with `ED` and it is missing a trailing slash.

The trailing slash no longer appears in EAPI=7 for `ED`, so it should be added to the ebuild. See [this guide](https://mgorny.pl/articles/the-ultimate-guide-to-eapi-7.html#d-ed-root-eroot-no-longer-have-a-trailing-slash) as a reference.

The correct line should be this:
```
gzip -9 "${ED}"/usr/share/cups/model/samsung/*.ppd || die
```

**Comment by Ri0n** [comment]
Thanks. Unfortunately I can't test the driver. I don't have this hardware anymore.
