### ISSUE TITLE
net-im/psi-9999[-xscreensaver] fails to build

### ISSUE THREAD

**Issue by corvus1** [rion-overlay/rion-overlay#240]
Builds fine with USE="xscreensaver". Same is true for the in-tree ebuild. Not sure if the dependency is not optional anymore, but I suspect that's what happened.

**Comment by Ri0n** [comment]
Hi @corvus1 
I don't know how the dependency got lost, but I've just readded it.

**Comment by Ri0n** [comment]
let me know if it works and I'll provide the fix to portage too

**Comment by corvus1** [comment]
It still fails with USE="-xscreensaver" in the exact same way.

**Comment by Ri0n** [comment]
thanks. should be fixed now.

**Comment by corvus1** [comment]
Did you... do anything? the last commit in the repo is 061f681d60abb3b35dcd199e0e7350d9276e9150

**Comment by Ri0n** [comment]
I changed in Psi itself.

**Comment by corvus1** [comment]
Oh, right! Sorry. Yes, it's fixed now, thanks.
