### ISSUE TITLE
games-action/oolite: Depends on unslotted `dev-lang/spidermonkey:0` (which doesn't exist any more)

### ISSUE THREAD

**Issue by Sophira** [rion-overlay/rion-overlay#241]
Hello,

I wanted to try installing **games-action/oolite** from your repository today, but it depends on `dev-lang/spidermonkey:0`, and the last unslotted version of that package was removed from the Gentoo tree in [August 2022](https://github.com/gentoo/gentoo/commit/776cb2bcedc5874c447b8082393473f20bab5790), so far as I can tell.

Just wanted to give you a heads-up! Thank you for maintaining this overlay.

**Comment by Ri0n** [comment]
Thanks for the report. Time to switch back to bundled -)
I'll check what I can do.

**Comment by Ri0n** [comment]
I'll abandon all arches but x86-64 to use prebuilt spidermonkey. 
other ways look quite painful.

**Comment by Ri0n** [comment]
I was able to avoid prebuilt stuff after all :)
builds now.
